let isRecording = false;
let lastUrl = location.href;

chrome.storage.local.get(['isRecording'], (result) => {
  isRecording = !!result.isRecording;
});

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'local' && changes.isRecording) {
    isRecording = !!changes.isRecording.newValue;
  }
});

/**
 * Fire-and-forget message to the service worker.
 * Content scripts in tabs that were open at the time the extension reloads
 * are stranded — `sendMessage` throws "Extension context invalidated".
 * This wrapper absorbs that and the unread lastError warning.
 */
function safeSend(message) {
  try {
    if (!chrome.runtime?.id) return;
    chrome.runtime.sendMessage(message, () => {
      void chrome.runtime.lastError;
    });
  } catch (_) {
    // context invalidated — stop trying.
  }
}

const SEMANTIC_TARGETS = 'a, button, [role="button"], [role="link"], input, textarea, select, label, [onclick], [tabindex]';

/**
 * Walk up from the deepest event target to the nearest semantic element
 * so generateSelectorInfo() receives the *intent unit* (the <button>),
 * not the decorative inner <span> the user happened to click.
 */
function semanticTarget(element) {
  if (!element || typeof element.closest !== 'function') return element;
  return element.closest(SEMANTIC_TARGETS) ?? element;
}

const SENSITIVE_AUTOCOMPLETE = new Set([
  'current-password', 'new-password',
  'cc-number', 'cc-csc', 'cc-exp', 'cc-name',
  'one-time-code'
]);

function isSensitiveInput(element) {
  if (!element) return false;
  if (element.type === 'password') return true;
  const ac = (element.getAttribute?.('autocomplete') || '').toLowerCase().trim();
  return SENSITIVE_AUTOCOMPLETE.has(ac);
}

// --- selector identification ------------------------------------------------

/**
 * Patterns that match auto-generated ids from common frameworks. These
 * ids churn between builds (or even between renders, for React `useId`),
 * so we treat them as non-identifying and fall back to other signals.
 */
const AUTO_ID_PATTERNS = [
  /^ember\d+/,
  /^mui-/,
  /^:r[0-9a-z]+:?$/i,
  /^radix-/,
  /^headlessui-/,
  /^__/,
  /-[a-f0-9]{6,}$/i,
  /^[a-f0-9]{8,}$/i,
  /^[a-zA-Z]+-\d{5,}$/
];

function isAutoGeneratedId(id) {
  if (!id || typeof id !== 'string') return true;
  return AUTO_ID_PATTERNS.some((p) => p.test(id));
}

function normalizeText(s, max = 80) {
  if (!s) return '';
  const cleaned = String(s).replace(/\s+/g, ' ').trim();
  return cleaned.length > max ? cleaned.slice(0, max - 1) + '…' : cleaned;
}

/**
 * Accessible name resolution following the simplified ARIA spec order:
 * aria-label > aria-labelledby (resolved) > title.
 * (Full WAI-ARIA name computation is more complex; this covers ~95% of
 * cases without dragging in a heavy dependency.)
 */
function getAccessibleName(element) {
  const aria = element.getAttribute?.('aria-label');
  if (aria && aria.trim()) return normalizeText(aria);

  const labelledBy = element.getAttribute?.('aria-labelledby');
  if (labelledBy) {
    const texts = labelledBy.split(/\s+/)
      .map((id) => document.getElementById(id)?.textContent)
      .filter(Boolean);
    if (texts.length) return normalizeText(texts.join(' '));
  }

  const title = element.getAttribute?.('title');
  if (title && title.trim()) return normalizeText(title);

  return '';
}

function getVisibleText(element) {
  const tag = element.tagName;
  if (tag === 'INPUT' || tag === 'TEXTAREA') {
    return normalizeText(element.getAttribute('placeholder'));
  }
  if (tag === 'IMG') {
    return normalizeText(element.getAttribute('alt'));
  }
  return normalizeText(element.textContent);
}

/**
 * For form elements, find the <label> that points to or wraps them.
 * Distinct from accessible name because pages often have a visible label
 * AND a separate aria-label; both signals help AI replay disambiguate.
 */
function getAssociatedLabel(element) {
  const formTags = ['INPUT', 'TEXTAREA', 'SELECT'];
  if (!formTags.includes(element.tagName)) return '';

  if (element.id) {
    try {
      const label = document.querySelector(`label[for="${CSS.escape(element.id)}"]`);
      if (label) return normalizeText(label.textContent);
    } catch (_) { /* invalid selector — skip */ }
  }

  const parentLabel = element.closest?.('label');
  if (parentLabel) {
    const clone = parentLabel.cloneNode(true);
    clone.querySelectorAll('input, textarea, select, button').forEach((el) => el.remove());
    return normalizeText(clone.textContent);
  }

  return '';
}

function getImplicitRole(element) {
  const tag = element.tagName?.toLowerCase();
  const type = (element.getAttribute?.('type') || '').toLowerCase();
  if (tag === 'a' && element.hasAttribute?.('href')) return 'link';
  if (tag === 'button') return 'button';
  if (tag === 'input') {
    if (type === 'submit' || type === 'button' || type === 'reset') return 'button';
    if (type === 'checkbox') return 'checkbox';
    if (type === 'radio') return 'radio';
    return 'textbox';
  }
  if (tag === 'textarea') return 'textbox';
  if (tag === 'select') return 'combobox';
  return '';
}

/**
 * Low-confidence fallback CSS path. Climbs up to maxDepth ancestors,
 * prefers stable ids, falls back to tag + first stable-looking class +
 * nth-of-type. Treats classes containing long hex/digits or `css-…`
 * (CSS-in-JS) as unstable and skips them.
 */
function buildCssSelector(element, maxDepth = 3) {
  const parts = [];
  let cur = element;
  let depth = 0;

  while (cur && cur.nodeType === 1 && depth < maxDepth) {
    if (cur.tagName === 'BODY' || cur.tagName === 'HTML') break;

    if (cur.id && !isAutoGeneratedId(cur.id)) {
      try {
        parts.unshift(`#${CSS.escape(cur.id)}`);
      } catch (_) {
        parts.unshift(cur.tagName.toLowerCase());
      }
      break;
    }

    let part = cur.tagName.toLowerCase();
    const stableClass = [...(cur.classList || [])].find((c) =>
      c.length >= 3 && c.length <= 30 &&
      !/\d{3,}/.test(c) &&
      !/^[a-f0-9]{8,}$/i.test(c) &&
      !c.startsWith('css-')
    );
    if (stableClass) {
      try { part += `.${CSS.escape(stableClass)}`; } catch (_) {}
    }

    if (cur.parentElement) {
      const siblings = [...cur.parentElement.children].filter((s) => s.tagName === cur.tagName);
      if (siblings.length > 1) {
        const idx = siblings.indexOf(cur) + 1;
        part += `:nth-of-type(${idx})`;
      }
    }

    parts.unshift(part);
    cur = cur.parentElement;
    depth++;
  }

  return parts.join(' > ');
}

/**
 * Build a rich identifier object for `element`. The caller has already
 * resolved `element` to a semantic target via semanticTarget(), so we
 * receive the <button>/<a>/<input> directly, never an inner span.
 *
 * Contract (popup.js depends on these key names):
 *   identifier signals: text > aria > id > name > css  (priority order)
 *   metadata:           tag, role, type, labelText, cssConfidence
 *
 * Privacy: this function handles *identification* only. The caller
 * captures value separately under a privacy gate (passwords redacted).
 */
function generateSelectorInfo(element) {
  if (!element || element.nodeType !== 1) return {};

  const info = {};
  const tag = (element.tagName || '').toLowerCase();
  if (tag) info.tag = tag;

  const explicitRole = element.getAttribute?.('role');
  const role = explicitRole || getImplicitRole(element);
  if (role) info.role = role;

  const type = element.getAttribute?.('type');
  if (type) info.type = type.toLowerCase();

  if (element.id && !isAutoGeneratedId(element.id)) {
    info.id = element.id;
  }

  const name = element.getAttribute?.('name');
  if (name) info.name = name;

  const aria = getAccessibleName(element);
  if (aria) info.aria = aria;

  const text = getVisibleText(element);
  if (text && text !== aria) info.text = text;

  const labelText = getAssociatedLabel(element);
  if (labelText && labelText !== aria && labelText !== text) {
    info.labelText = labelText;
  }

  const css = buildCssSelector(element);
  if (css) {
    info.css = css;
    info.cssConfidence = 'low';
  }

  return info;
}

// --- event capture ----------------------------------------------------------

function pushEvent(type, element, extras = {}) {
  if (!isRecording) return;
  const navigated = location.href !== lastUrl;
  if (navigated) {
    safeSend({
      action: 'recordEvent',
      event: { type: 'navigate', timestamp: Date.now(), url: location.href, from: lastUrl }
    });
    lastUrl = location.href;
  }
  safeSend({
    action: 'recordEvent',
    event: {
      type,
      timestamp: Date.now(),
      url: location.href,
      selector: element ? generateSelectorInfo(element) : null,
      ...extras
    }
  });
}

document.addEventListener('click', (e) => {
  pushEvent('click', semanticTarget(e.target));
}, true);

document.addEventListener('change', (e) => {
  const raw = e.target;
  if (!raw) return;
  const tag = (raw.tagName || '').toUpperCase();
  if (tag !== 'INPUT' && tag !== 'TEXTAREA' && tag !== 'SELECT') return;

  const target = semanticTarget(raw);
  const inputType = (raw.type || '').toLowerCase();

  if (inputType === 'checkbox' || inputType === 'radio') {
    pushEvent('input', target, { value: !!raw.checked, inputType });
    return;
  }

  if (isSensitiveInput(raw)) {
    pushEvent('input', target, { value: '[REDACTED]', sensitive: true, inputType });
    return;
  }

  pushEvent('input', target, { value: raw.value, inputType });
}, true);

document.addEventListener('submit', (e) => {
  pushEvent('submit', semanticTarget(e.target));
}, true);
